### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-web-authn-token#1]

**Comment by mandyvenables** [comment]
There was a test suite set up [in this commit](https://github.com/digitalbazaar/bedrock-web-authn-token/commit/b99cc289fc3a7a10ba21a93bb1d6aecd22859255), but it should be expanded upon.

**Comment by aljones15** [comment]
Closing this as we now have basic tests. Next issue to expand the tests: https://github.com/digitalbazaar/bedrock-web-authn-token/issues/9
